spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wow_items?serverTimezone=${spring.jpa.properties.hibernate.jdbc.time_zone}
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: false