INSERT INTO source (id, type, location, target, wow_head_id) VALUES (1, 'DUNGEON', 'Stratholme', 'Magistrate Barthilas', 10435);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (2, 'QUEST', 'Darkmoon Faire', '1200 Tickets - Orb of the Darkmoon', 7940);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (3, 'DUNGEON', 'Blackrock Depths', 'Warder Stilgiss', 9041);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (4, 'DUNGEON', 'Stratholme', 'Archivist Galford', 10811);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (5, 'PROFESSION', 'Tailoring', 'Pattern:Robe of the Archmage', 14513);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (6, 'PVP', 'Warsong Gulch', 'Warsong Gulch exalted', null);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (7, 'DUNGEON', 'Lower Blackrock Spire', 'Highlord Omokk', 9196);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (8, 'DUNGEON', 'Lower Blackrock Spire', 'Quartermaster Zigris', 9736);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (9, 'DUNGEON', 'Blackrock Depths', 'Ok''thor the Breaker', 9030);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (10, 'PVP', 'PvP Quartermaster', 'PvP Rank 7 Reward', null);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (11, 'WORLDBOSS', 'Azshara', 'Draconic Mageweaver', 6131);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (12, 'DUNGEON', 'Upper Blackrock Spire', 'Jed Runewatcher', 10509);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (13, 'QUEST', 'Upper Blackrock Spire', 'For The Horde!', 4974);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (14, 'DUNGEON', 'Scholomance', 'Darkmaster Gandling', 1853);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (15, 'CONTAINER', 'Dire Maul', 'Gordok Tribute', 179564);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (16, 'PVP', 'Alterac Valley', 'Alterac Valley exalted', null);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (17, 'DUNGEON', 'Blackrock Depths', 'Lord Incendius', 9017);
INSERT INTO source (id, type, location, target, wow_head_id) VALUES (18, 'QUEST', null, 'Hero of the Stormpike', 8271);

INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (1, 'Crimson Felt Hat', 18727, 'HEAD', 1, 1, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (2, 'Tome of the Ice Lord', 19310, 'OFFHAND', 1, 16, 0);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (3, 'Flameweave Cuffs', 11766, 'WRIST', 1, 17, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (4, 'Boreal Mantle', 11782, 'SHOULDERS', 1, 3, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (5, 'Orb of the Darkmoon', 19426, 'NECK', 1, 2, 0);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (6, 'Archivist Cape', 13386, 'BACK', 1, 4, 0);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (7, 'Robe of the Archmage', 14152, 'CHEST', 1, 5, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (8, 'Skyshroud Leggings', 23304, 'LEGS', 1, 7, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (9, 'Hands of Power', 13253, 'HAND', 1, 8, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (10, 'Ban''thok Sash', 11662, 'WAIST', 1, 9, 0);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (11, 'Knight-Lieutenant''s Silk Walkers', 23291, 'FEET', 1, 10, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (12, 'Freezing Band', 942, 'RING', 1, 11, 0);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (13, 'Briarwood Reed', 12930, 'TRINKET', 1, 12, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (14, 'Eye of the Beast', 13968, 'TRINKET', 1, 13, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (15, 'Witchblade', 13964, 'MAINHAND', 1, 14, 0);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (16, 'Rod of the Ogre Magi', 18534, 'MAINHAND', 1, 15, 1);
INSERT INTO item (id, name, wow_head_id, slot, phase, source_id, own) VALUES (17, 'Wand of Biting Cold', 19108, 'WARD', 1, 18, 1);
